language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG && pwd
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install apt-transport-https && sudo apt-get install -y llvm-3.4 llvm-3.4-dev && sudo apt-get install cmake libboost-thread-dev libboost-system-dev libboost-test-dev; fi
  - bin/cpp_prereq.sh
  - cd cpp && ./.cmake.gen.sh

script:
  - cd cmake_build/debug && cmake && ctest
  - cd cmake_build/release && cmake && ctest  

  