language: cpp

services:
  - mongodb
  
compiler:
  - gcc

before_install:
  - echo $LANG && pwd
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install apt-transport-https && sudo apt-get install -y llvm-3.4 llvm-3.4-dev && sudo apt-get install cmake; fi
  - sudo apt-get update
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo apt-get install libboost1.54-all-dev
  - bin/cpp_prereq.sh
  - bin/install_cmake.sh
  - bin/install_mongo.sh  
  - bin/install_benchmark.sh  
  - bin/install_hdf5.sh
  - cd cpp && ./.cmake.gen.sh && cd -

script:
  - cd cmake_build/debug && make VERBOSE=1 && ctest && cd -
  - cd cmake_build/release && make VERBOSE=1 && ctest && cd -

  