language: cpp

compiler:
  - clang

before_install:
  - echo $LANG && pwd
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install apt-transport-https && sudo apt-get install -y llvm-3.4 llvm-3.4-dev && sudo apt-get install cmake; fi
  - sudo add-apt-repository ppa:boost-latest/ppa -y; sudo apt-get update; sudo apt-get install boost1.55
  - sudo apt-get install clang-3.6
  - bin/cpp_prereq.sh
  - cd cpp && ./.cmake.gen.sh && cd -

script:
  - cd cmake_build/debug && make && ctest
  - cd cmake_build/release && make && ctest  

  