name: fcs
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  ebisu: "any"
  ebisu_cpp: "any"
  path: "any"

# custom <fcs dependencies>

  collection: ">=1.0.0"

  ebisu:
   git: git://github.com/patefacio/ebisu
   
  ebisu_cpp:
    git: git://github.com/patefacio/ebisu_cpp

  ebisu_cpp_db:
    git: git://github.com/patefacio/ebisu_cpp_db
    
  magus:
   git: git://github.com/patefacio/magus

# end <fcs dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"

# custom <fcs dev dependencies>
# end <fcs dev dependencies>

dependency_overrides:
# custom <fcs dependency overrides>

#  magus:
#   path: /home/dbdavidson/dev/open_source/magus

#  ebisu:
#   path: /home/dbdavidson/dev/open_source/ebisu

#  ebisu_cpp:
#   path: /home/dbdavidson/dev/open_source/ebisu_cpp

#  ebisu_cpp_db:
#   path: /home/dbdavidson/dev/open_source/ebisu_cpp_db
   
# end <fcs dependency overrides>

transformers:

# custom <fcs transformers>
# end <fcs transformers>

