name: fcs
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  ebisu:
      path: /Users/dbdavidson/dev/open_source/ebisu
  ebisu_cpp:
      path: /Users/dbdavidson/dev/open_source/ebisu_cpp
  path: ">=1.2.2 < 1.10.0"

# custom <fcs dependencies>

  collection: ">=1.0.0"

# end <fcs dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"

# custom <fcs dev dependencies>
# end <fcs dev dependencies>

transformers:

# custom <fcs transformers>
# end <fcs transformers>

