name: cpp_ebisu
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  ebisu: "any"
  ebisu_cpp: "any"
  path: "any"

# custom <ebisu dependencies>

  collection: ">=1.0.0"
  quiver: ">=0.21.0<0.22.0"  
  id: "^1.0.10"  
  ebisu: "^0.6.1"
  ebisu_cpp: "^0.3.2"
  ebisu_cpp_db: "^0.0.7"
   
# end <ebisu dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"

# custom <ebisu dev dependencies>
# end <ebisu dev dependencies>

dependency_overrides:
# custom <ebisu dependency overrides>

#  id:
#    path: /home/dbdavidson/dev/open_source/id

#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu

  ebisu: "^0.6.1"

  ebisu_cpp:
    path: /home/dbdavidson/dev/open_source/ebisu_cpp

  ebisu_cpp_db:
    path: /home/dbdavidson/dev/open_source/ebisu_cpp_db
    
# end <ebisu dependency overrides>

transformers:

# custom <ebisu transformers>
# end <ebisu transformers>

