name: cpp_ebisu
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  ebisu: "any"
  ebisu_cpp: "any"
  path: "any"

# custom <ebisu dependencies>

  collection: ">=1.0.0"
  quiver: ">=0.21.0<0.22.0"  
  id: "^1.0.15"  
  ebisu: #"^0.7.3"
    path: ../../ebisu  

  ebisu_cpp: #"^0.3.22"
    path: ../../ebisu_cpp


  ebisu_cpp_db: #"^0.0.10"
    git: git://github.com/patefacio/ebisu_cpp_db

# end <ebisu dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"

# custom <ebisu dev dependencies>
# end <ebisu dev dependencies>

dependency_overrides:
# custom <ebisu dependency overrides>

  ebisu:
    path: ../../ebisu

  ebisu_cpp: #"^0.3.22"
    path: ../../ebisu_cpp

# end <ebisu dependency overrides>

transformers:

# custom <ebisu transformers>
# end <ebisu transformers>

